name: 'Create deployment on GitHub'
branding:
  icon: shopping-bag
  colour: green
description: 'Sends a request to GitHub in order to track deployment'
inputs:
  ref:
    description: 'Branch to be deployed'
    required: true
  sha:
    description: 'Commit sha to be deployed'
    required: true
  environment:
    description: 'Environment the deploy will happen in'
    required: true
  preview_url:
    description: 'Preview URL'
    required: true
  creator:
    description: 'The creator of the commit to be deployed'
    required: true
  description:
    description: 'Description of the deploy'
    default: ''
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
